// Seed data — sample shows + supporting datasets used on first run and by
// the discover/search/me screens. Real saved shows go through db.js.

export const SEED_SHOWS = [
  {
    id: 's-2026-04-12',
    type: 'concert',
    artist: 'Mitski', support: ['Quinnie'],
    date: '2026-04-12', dateLabel: 'Apr 12, 2026',
    venue: '工人体育馆', venueEn: "Workers' Gymnasium",
    city: '北京', cityEn: 'Beijing', country: 'CN',
    geo: [39.927, 116.453],
    price: 880, currency: '¥',
    seat: 'Sec 12 · Row J · Seat 18', ticketNo: 'NO. 002418',
    rating: 5,
    mood: ['哭了', '一辈子一次'], moodEn: ['cried', 'once-in-a-life'],
    company: ['Lin', 'Wei'], setlistCount: 19,
    notes: '她唱 A Pearl 的时候我哭崩了。最后 returning the dog 全场跟唱，灯光打到天花板的时候我突然觉得整个二十几岁都值了。',
    cover: 'sunset', accent: 'red',
  },
  {
    id: 's-2026-03-22',
    type: 'concert',
    artist: '万能青年旅店', support: [],
    date: '2026-03-22', dateLabel: 'Mar 22, 2026',
    venue: 'MAO Livehouse', venueEn: 'MAO Livehouse',
    city: '上海', cityEn: 'Shanghai', country: 'CN',
    geo: [31.232, 121.469],
    price: 480, currency: '¥',
    seat: 'Standing · Floor', ticketNo: 'NO. 001907',
    rating: 5,
    mood: ['前排', '汗流浃背'], moodEn: ['front row', 'soaked'],
    company: ['solo'], setlistCount: 14,
    notes: '《杀死那个石家庄人》前奏一响全场炸了。董二千的吉他比专辑里更躁，鼓手简直在拆架子鼓。',
    cover: 'amber', accent: 'amber',
  },
  {
    id: 's-2026-02-08',
    type: 'theatre',
    artist: '茶馆', support: ['北京人艺'],
    date: '2026-02-08', dateLabel: 'Feb 08, 2026',
    venue: '首都剧场', venueEn: 'Capital Theatre',
    city: '北京', cityEn: 'Beijing', country: 'CN',
    geo: [39.918, 116.413],
    price: 380, currency: '¥',
    seat: '一层 · 12排 · 6座', ticketNo: 'NO. 001702',
    rating: 5,
    mood: ['百年', '父母同行'], moodEn: ['classic', 'with parents'],
    company: ['Mom', 'Dad'], setlistCount: 0,
    notes: '老舍的话剧第一次在剧场里看，王利发那句"我爱咱们的国呀"出来的瞬间整个剧场都没人喘气。',
    cover: 'cool', accent: 'ink',
  },
  {
    id: 's-2025-12-31',
    type: 'concert',
    artist: '新裤子', support: ['刺猬', '海龟先生'],
    date: '2025-12-31', dateLabel: 'Dec 31, 2025',
    venue: '梅赛德斯-奔驰文化中心', venueEn: 'Mercedes-Benz Arena',
    city: '上海', cityEn: 'Shanghai', country: 'CN',
    geo: [31.187, 121.491],
    price: 680, currency: '¥',
    seat: 'Sec B · Row 14 · Seat 32', ticketNo: 'NO. 001501',
    rating: 4,
    mood: ['跨年', '人挤人'], moodEn: ['NYE', 'crowded'],
    company: ['Lin', 'Wei', 'Mei', 'Tao'], setlistCount: 22,
    notes: '跨年场。彭磊唱《没有理想的人不伤心》倒计时进入 2026。烟火太多，眼睛有点呛。',
    cover: 'magenta', accent: 'red',
  },
  {
    id: 's-2025-11-15',
    type: 'concert',
    artist: 'Phoebe Bridgers', support: ['MUNA'],
    date: '2025-11-15', dateLabel: 'Nov 15, 2025',
    venue: 'Greek Theatre', venueEn: 'Greek Theatre',
    city: 'Berkeley', cityEn: 'Berkeley', country: 'US',
    geo: [37.873, -122.254],
    price: 110, currency: '$',
    seat: 'Sec C · Row 22', ticketNo: 'NO. 001321',
    rating: 5,
    mood: ['户外', '冷'], moodEn: ['outdoor', 'cold'],
    company: ['Anna'], setlistCount: 17,
    notes: '加州十一月的露天场，冷得发抖但 Moon Song 一开始就忘了冷。',
    cover: 'rose', accent: 'rose',
  },
  {
    id: 's-2025-10-04',
    type: 'concert',
    artist: 'Fred again..', support: [],
    date: '2025-10-04', dateLabel: 'Oct 04, 2025',
    venue: 'Printworks', venueEn: 'Printworks',
    city: 'London', cityEn: 'London', country: 'UK',
    geo: [51.494, -0.052],
    price: 65, currency: '£',
    seat: 'Standing · GA', ticketNo: 'NO. 001188',
    rating: 5,
    mood: ['蹦', '凌晨3点'], moodEn: ['danced', '3am'],
    company: ['Sam', 'Jess'], setlistCount: 0,
    notes: '', cover: 'cyan', accent: 'ink',
  },
  {
    id: 's-2025-08-19',
    type: 'standup',
    artist: '鸟鸟 · 单口专场', support: [],
    date: '2025-08-19', dateLabel: 'Aug 19, 2025',
    venue: '笑果工厂', venueEn: 'Xiaoguo Factory',
    city: '上海', cityEn: 'Shanghai', country: 'CN',
    geo: [31.221, 121.467],
    price: 280, currency: '¥',
    seat: '池座 · A区 · 8排', ticketNo: 'NO. 000942',
    rating: 5,
    mood: ['笑出眼泪'], moodEn: ['cry-laughing'],
    company: ['Lin'], setlistCount: 0,
    notes: '社恐讲社恐，从头笑到尾。',
    cover: 'olive', accent: 'amber',
  },
  {
    id: 's-2025-07-06',
    type: 'classical',
    artist: '上海交响乐团 · 马勒第二', support: ['余隆 指挥'],
    date: '2025-07-06', dateLabel: 'Jul 06, 2025',
    venue: '上海交响乐团音乐厅', venueEn: 'Shanghai Symphony Hall',
    city: '上海', cityEn: 'Shanghai', country: 'CN',
    geo: [31.221, 121.467],
    price: 380, currency: '¥',
    seat: '一层 · 9排 · 12座', ticketNo: 'NO. 000810',
    rating: 5,
    mood: ['复活', '震撼'], moodEn: ['resurrection', 'awe'],
    company: ['Wei'], setlistCount: 0,
    notes: '第五乐章合唱进来的时候眼泪刹不住。',
    cover: 'electric', accent: 'ink',
  },
  {
    id: 's-2025-05-23',
    type: 'concert',
    artist: 'Radiohead', support: [],
    date: '2025-05-23', dateLabel: 'May 23, 2025',
    venue: 'Madison Square Garden', venueEn: 'MSG',
    city: 'New York', cityEn: 'New York', country: 'US',
    geo: [40.750, -73.993],
    price: 220, currency: '$',
    seat: 'Sec 207 · Row 8', ticketNo: 'NO. 000654',
    rating: 5,
    mood: ['传奇', '哭'], moodEn: ['legendary', 'cried'],
    company: ['Anna', 'Jay'], setlistCount: 24,
    notes: 'How to Disappear Completely 的时候整个 garden 安静得像一座教堂。',
    cover: 'kid-a', accent: 'red',
  },
]

// Cities for map
export const MAP_CITIES = [
  { name: '上海', en: 'Shanghai', lat: 31.23, lng: 121.47, count: 18 },
  { name: '北京', en: 'Beijing', lat: 39.92, lng: 116.4, count: 9 },
  { name: '台北', en: 'Taipei', lat: 25.04, lng: 121.52, count: 4 },
  { name: '东京', en: 'Tokyo', lat: 35.68, lng: 139.69, count: 3 },
  { name: 'London', en: 'London', lat: 51.51, lng: -0.13, count: 5 },
  { name: 'Berlin', en: 'Berlin', lat: 52.52, lng: 13.4, count: 2 },
  { name: 'New York', en: 'New York', lat: 40.71, lng: -74.0, count: 3 },
  { name: 'Berkeley', en: 'Berkeley', lat: 37.87, lng: -122.25, count: 1 },
  { name: 'Austin', en: 'Austin', lat: 30.27, lng: -97.74, count: 2 },
]

export const YEAR_BARS = [
  { year: 2020, count: 0 },
  { year: 2021, count: 2 },
  { year: 2022, count: 4 },
  { year: 2023, count: 8 },
  { year: 2024, count: 14 },
  { year: 2025, count: 12 },
  { year: 2026, count: 7 },
]

export const DISCOVER = [
  { id: 'd-1', artist: 'Big Thief', when: 'Jun 14', venue: '上海 · MAO',
    reason: '你听过 Adrianne Lenker 的 solo 专辑', accent: 'amber' },
  { id: 'd-2', artist: 'Caroline Polachek', when: 'Jul 02', venue: '台北 · Legacy',
    reason: '北京/上海/台北巡演', accent: 'rose' },
  { id: 'd-3', artist: '回春丹', when: 'May 28', venue: '杭州 · MAO',
    reason: '在你常去的城市', accent: 'red' },
]

export const SEARCH_HISTORY = ['Mitski', '草东', 'Fred again', 'MAO Livehouse', '北京']
export const SEARCH_TAGS = ['哭了', '前排', '一辈子一次', '出差顺便', '跨年']

export const SAMPLE_MEDIA = [
  { id: 'm1', kind: 'photo', cover: 'sunset', caption: '开场前', captionEn: 'before doors' },
  { id: 'm2', kind: 'video', cover: 'magenta', duration: '0:42', caption: 'A Pearl', captionEn: 'A Pearl' },
  { id: 'm3', kind: 'photo', cover: 'rose', caption: '安可', captionEn: 'encore' },
  { id: 'm4', kind: 'video', cover: 'amber', duration: '1:08', caption: '跟唱', captionEn: 'singalong' },
  { id: 'm5', kind: 'photo', cover: 'cool', caption: '票根', captionEn: 'my stub' },
  { id: 'm6', kind: 'photo', cover: 'electric', caption: '灯光', captionEn: 'lights' },
  { id: 'm7', kind: 'video', cover: 'kid-a', duration: '0:18', caption: '散场', captionEn: 'walking out' },
]

export const SAMPLE_SETLIST = [
  { title: 'Bug Like an Angel' },
  { title: 'Working for the Knife' },
  { title: 'A Pearl' },
  { title: 'I Bet on Losing Dogs' },
  { title: 'Nobody' },
  { title: 'Washing Machine Heart' },
  { title: 'My Love Mine All Mine', encore: true },
]
